### ISSUE TITLE
Functions should be renamed to reflect that we use "scenario" to refer to tasks now

### ISSUE THREAD

**Issue by larskotthoff** [berndbischl/coseal-algsel-benchmark-repo#101]

**Comment by larskotthoff** [comment]
This should be a simple search and replace and I'd be happy to do it. This will obviously change a lot of things, so I don't want to do it while somebody else is working on the code. When would be a good time to do this?

**Comment by kerschke** [comment]
I don't intent to work on it this week(end). Thus, from my point of view you can do it any time you want - depending on Bernd ;-)

**Comment by berndbischl** [comment]
On 7. Mai 2014 11:12:17 MESZ, kerschke notifications@github.com wrote:

> I don't intent to work on it this week(end). Thus, from my point of
> view you can do it any time you want - depending on Bernd ;-)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/berndbischl/coseal-algsel-benchmark-repo/issues/101#issuecomment-42405108

Same here. Go ahead.

**Comment by larskotthoff** [comment]
Done in 116cdfbf1084b957d899eb1aeb096d635dec11c3 -- reopen if I broke anything.
