### ISSUE TITLE
Add explanation texts on HTML pages

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#14]
Some plots and tables are a bit harder to understand. 

Add _brief_ and _good_ explanations to the sections when needed.

**Comment by kerschke** [comment]
added a few explanations

**Comment by kerschke** [comment]
Is there anything else we need to explain more detailed?

**Comment by berndbischl** [comment]
Closing this for now, lets open issues when we discover that something is indeed bad or missing.
