### ISSUE TITLE
EDA: correlation between algorithms

### ISSUE THREAD

**Issue by mlindauer** [berndbischl/coseal-algsel-benchmark-repo#16]
see correlation matrix in http://www.cs.ubc.ca/labs/beta/Projects/SATzilla/SAT12-EvaluatingSolverContributions.pdf
maybe there are also some other nice ideas in there

**Comment by mlindauer** [comment]
marginal contribution for orcale would be also nice

**Comment by berndbischl** [comment]
Marius, can you add 1-2 sentences what you mean here:

> marginal contribution for orcale would be also nice

**Comment by berndbischl** [comment]
corr. plots are already done
