### ISSUE TITLE
arff files look different depending on committer

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#18]
So far, we have the problem that factor levels are shown different, depending on the committer (probably due to use of different programs).

Submissions by Marius look like this:
@ATTRIBUTE instance_id STRING
@ATTRIBUTE repetition NUMERIC
@ATTRIBUTE nvarsOrig {ok, timeout, memout, presolved, crash, other}
@ATTRIBUTE nclausesOrig {ok, timeout, memout, presolved, crash, other}
@ATTRIBUTE presolved {true,false}

Submissions by Pascal look like this:
@attribute instance_id string
@attribute repetition numeric
@attribute dim {'ok','timeout','memout','presolved','crash','other'}
@attribute fid {'ok','timeout','memout','presolved','crash','other'}
@attribute presolved {'TRUE','FALSE'}

We should find a way to explicitly define how the files have to look like, i.e. should for instance TRUE/FALSE be represented as 'TRUE'/'FALSE', true/false, ...?!
What about the other attributes?
Should we also check whether names such as ATTRIBUTE, STRING, etc. are written in capital letters?

a) Clearly specify those points in the specs tex.
b) Fit arff-files to the specifications from a)

**Comment by berndbischl** [comment]
For the types like STRING / string this is likely no problem, as long as we can parse the files.

Same holds for {'ok','timeout','memout','presolved','crash','other'} vs  {ok, timeout, memout, presolved, crash, other}

But factor levels must be specified correctly case-sensitive so, either true / false or TRUE FALSE depending on what we have in the paper.

**Comment by kerschke** [comment]
Just corrected the three data sets (bbob, csp, qbf) that were different to the other ones:
- apostrophes (') were removed
- TRUE / FALSE is now true / false
- STRING, NUMERIC is always written in capital letters
- the arff-commands "@..." are also written in capital letters
