### ISSUE TITLE
Warnings in algo density plot

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#23]
There are warnings in front of the density plot for the algos of sat12-indu:
 Warning: Removed 436 rows containing non-finite values (stat_density).
 Warning: Removed 461 rows containing non-finite values (stat_density).
 Warning: Removed 276 rows containing non-finite values (stat_density).

Either tackle that problem or find a shorter output for all those warnings...

**Comment by berndbischl** [comment]
Remove NAs manually on pages. 

METION that in explanation on each page where it is done

**Comment by kerschke** [comment]
Removed NAs manually and added a brief note at the beginning of the concerned sections.
