### ISSUE TITLE
Error messages in Feature HTML pages

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#26]
The feature performance overviews (I only checked the first two: bbob and csp) show R error-messages stating that they could not find the corresponding R-functions (summarizeFeatureRunstatus and lookForDuplicates). But, those files are in the repo - thus, they should not produce any errors.

**Comment by berndbischl** [comment]
1) Simple renaming issue. Why not check the sources and then quickly fix it?

2) lookForDuplicates (now: checkDuplicazedInstances) was so slow, I had to completely rewrite it from scratch.....
