### ISSUE TITLE
Write page to explain experimental setup of benchmark results

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#27]
Text page, so everybody knows what was done

**Comment by berndbischl** [comment]
Maybe just do this in the upcoming paper. 
Otherwise just duplicated work........

**Comment by berndbischl** [comment]
We will put this into the paper and reference that. Closing.

**Comment by berndbischl** [comment]
I changed my mind. 

MUST be on webpage for easy access. 

Do it later, when all is decided for paper.

**Comment by larskotthoff** [comment]
First attempt in 3d9e71db6e

**Comment by berndbischl** [comment]
Marius, can you please check the wiki page?

**Comment by mlindauer** [comment]
I read it, fixed some typos and added small things.

**Comment by berndbischl** [comment]
Ok if you like it, it can be closed
