### ISSUE TITLE
format cv splits must be passed to llama, so llama respects them

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#30]

**Comment by berndbischl** [comment]
Lars said:

"How do you want to handle this? One
relatively easy way of implementing this in LLAMA would be to pass lists instead
of single data frames for features, times, success. Those lists would represent
the folds. Then the user would of course have to make sure that they match, i.e.
first feature data frame corresponds to first time data frame etc."

**Comment by berndbischl** [comment]
Wouldnt it be more natural to code this (in algselbbench)

convertCVSplitsToLLama(astask, coseal.cv.split.data.frame)

or 

convertCVSplitsToLLama(llama.task, coseal.cv.split.data.frame)

--> same result as your cvFolds method?

**Comment by larskotthoff** [comment]
What data do you want to pass to LLAMA? I guess there's two separate things here -- first how it's handled in algselbench and second how this information is passed to LLAMA.

**Comment by berndbischl** [comment]
It is like this 

We start here:
We parse the the data and get:
-  an algselbench:ASTask object 
- cv-splits data.frame.

We need to do 
- get the output of llama::input. We already can do that with convertToLlama
- now split this up in the way llama::cvFolds does. But with the cv-splits data.frame defining the splits. (I currently just split with cvFolds in a new way)

So I suggest you write
convertToLlamaCVFolds(llama.input, cv.splits.data.frame) --> 
  result with same structure as result of cvFolds

It should be to a larger degree some copy-paste from llama::cvFolds I guess?

Where you put this function I do not care too much, but I would naturally suggest into algselbench.

**Comment by larskotthoff** [comment]
Ok, just to make sure that I understand -- where are the splits coming from? Because if you're splitting in algselbench (i.e. data is read unsplit), then you might as well split in llama later, no?

**Comment by berndbischl** [comment]
We have an ARFF file in the format specification, containing the splits,  which resides on the server?

**Comment by berndbischl** [comment]
Although I am unsure whether we have created those already :)
Lemme check.

**Comment by berndbischl** [comment]
I guess we dont. 
i will write a method for that now, so we can create the files for the tasks already there. But the format of that data frame is already in the specs.

**Comment by larskotthoff** [comment]
Ok, that's why I was confused. I'll have a look at implementing this.

**Comment by berndbischl** [comment]
I have uploaded the cv.arff files into coseal svn

You might want to look at 

algselbench/R/createCVSplits
server_scripts/createCVSplitFiles

**Comment by larskotthoff** [comment]
Added file and function to convert to LLAMA with folds in 2eb554ec9c1e1067d8c14ed315ee3c834ae92775. I wasn't able to test this as `convertToLlama` doesn't work on my machine -- complains that `impute` isn't defined. Do I need to install something for this to work?

The way the function is currently implemented is that it expects the folds as returned by `createCVSplits` to be given as an argument -- alternatively I could call that function myself. Thoughts?

**Comment by kerschke** [comment]
Did you check out the current mlr version and the coseal-algsel-benchmark-repo? In that case, impute _should_ work.

**Comment by berndbischl** [comment]
I am currently preparing a new major release.

"impute" is new and only in the github devel version.

Run: 

devtools::install_github("mlr", username="berndbischl")

(This is mentioned in the README / web page of all my github packages, see detailed installation instruction there)

**Comment by larskotthoff** [comment]
Ok, if I do that I get the error

```
Error : package 'ParamHelpers' 1.1-36 was found, but >= 1.2 is required by 'mlr'
```

I've just installed ParamHelpers again and this version seems to be the latest I can get through `install.packages()`. How would I upgrade to the version needed by mlr?

**Comment by larskotthoff** [comment]
Ok, that's fixed (with help from Bernd). Now I'm getting

```
could not find function "convertMatrixType"
  1: checkDuplicatedInstances(testtask1)
```

when I run `make check`. Doesn't seem to have anything to do with that I've done?

**Comment by kerschke** [comment]
Now, it's a problem of BBmisc. You probably have to update that one as well (analogue to ParamHelpers and mlr). That's the problem, when working with various developers versions :-)

**Comment by larskotthoff** [comment]
Ok, now everything works and the test I've written passes! I've run `make check` and it didn't complain about anything else, so I consider this done. Please comment if I missed something.

**Comment by berndbischl** [comment]
Dang, sorry.

Hopefully that was all. Ok you said it  works :)

Great + Thx!

**Comment by berndbischl** [comment]
The function convertToLlamaCVFolds only works when we have 1 repetition in the CV.

I added a unit test to show this.

```
ast = parseASTask("/home/bischl/cos/coseal/data/qbf_2011")
cv.splits = createCVSplits(ast, reps=2, folds=2)
convertToLlamaCVFolds(ast, cv.splits = cv.splits)


ading algselbench
Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In split.default(x = seq_len(nrow(x)), f = f, drop = drop, ...) :
  data length is not a multiple of split variable
2: non-unique values when setting 'row.names': ‘1000’, ‘1001’, ‘1002’, ‘1003’, ‘1004’, ‘1005’, ‘1006’, ‘1007’, ‘1008’, ‘1009’, ‘1010’, ‘1011’, ‘1012’, ‘1013’, ‘1014’, ‘1015’, ‘1016’, ‘1017’, ‘1018’, ‘1019’, ‘1020’, ‘1021’, ‘1022’, ‘1023’, ‘1024’, ‘1025’, ‘1026’, ‘1027’, ‘1028’, ‘1029’, ‘1030’, ‘1031’, ‘1032’, ‘1033’, ‘1034’, ‘1035’, ‘1036’, ‘1037’, ‘1038’, ‘1039’, ‘1040’, ‘1041’, ‘1042’, ‘1043’, ‘1044’, ‘1045’, ‘1046’, ‘1047’, ‘1048’, ‘1049’, ‘1050’, ‘1051’, ‘1052’, ‘1053’, ‘1054’, ‘1055’, ‘1056’, ‘1057’, ‘1058’, ‘1059’, ‘1060’, ‘1061’, ‘1062’, ‘1063’, ‘1064’, ‘1065’, ‘1066’, ‘1067’, ‘1068’, ‘1069’, ‘1070’, ‘1071’, ‘1072’, ‘1073’, ‘1074’, ‘1075’, ‘1076’, ‘1077’, ‘1078’, ‘1079[... truncated] 

```

**Comment by larskotthoff** [comment]
What is the intended behaviour with multiple repetitions?

**Comment by berndbischl** [comment]
I would have preferred this, to stabilize the avg. performance value.

It is in the interface anyway....

Is it hard to adapt this?

**Comment by larskotthoff** [comment]
So if there are multiple repetitions, the mean value across them should be used?

**Comment by berndbischl** [comment]
Yes. You basically do the whole CV stuff a couple of times, estimate performance per single CV.
Then take the mean of these single CV estimates. 

You would do this if you would notice (larger) variance in repeating a normal CV.

Technically, if you do a 5 x 10 CV with 10 folds, you can also simply average the estimates from the 50 folds as this is (nearly) the same thing. I would think that by using that trick this requires nearly no change in llama?

**Comment by larskotthoff** [comment]
Wait, so you want to create a set of folds for each repetition and not one set of folds with the mean values across all repetitions for performance?

**Comment by berndbischl** [comment]
I would create simply 50 folds like I said above, and average performance across these.

IF llama can accept this. Because this would be the easiest way.

**Comment by larskotthoff** [comment]
Well the problem is that that one llama data frame is supposed to contain only one data set (or repetition). I could return a list of llama data frames from the conversion method, but training models and averaging the performance over them would be te user's task.

**Comment by berndbischl** [comment]
We will do one CV repetition then ..... :(

**Comment by berndbischl** [comment]
I can maybe hack this into the BatchExperiments code I have. But I will do this later, if at all.

**Comment by larskotthoff** [comment]
How do you want me to handle this in the conversion function? Throw an error if there's more than 1 repetition?

**Comment by berndbischl** [comment]
I will add an arg check now, working on the code anyway.

And have a separate issue here, so we dont forget this.

**Comment by berndbischl** [comment]
Closing and adding new issue.
