### ISSUE TITLE
bug in csp set

### ISSUE THREAD

**Issue by mlindauer** [berndbischl/coseal-algsel-benchmark-repo#35]
these two performance data are strange (found by checker):

2-fullins-5-6.xml.watchless.minion.gz,1,standard,256.248044,timeout
2-fullins-5-6.xml.watchless.minion.gz,1,learning,?,ok

The first one should have an ? because it is an timeout
and the second one should have a runtime value because the status is ok.

Since pascal is the translator, I assign this to him.

**Comment by larskotthoff** [comment]
The status looks like it's reversed -- I just had a look at the raw data and the time for standard is ok and learning timed out.

**Comment by kerschke** [comment]
I agree.. I just checked the raw data as well. I will change the csp-set accordingly.

**Comment by mlindauer** [comment]
The issue was not really solved.
The given example was not the only example of this issue.
Please fix it again!

**Comment by kerschke** [comment]
In which way is the csp set still causing problems?

**Comment by mlindauer** [comment]
please open
http://coseal.googlecode.com/svn/trunk/data/csp_2010/algorithm_runs.arff

and search for the combination:
?,ok
You will find the problems ;-)

There cannot be an unknown runtime in combination with "ok" status.

**Comment by kerschke** [comment]
Ok. Now it _should_ be correct ;-)

**Comment by kerschke** [comment]
I'll close it for now. If anybody finds something suspicious about the data set, we can reopen it again.
