### ISSUE TITLE
bug in bbob

### ISSUE THREAD

**Issue by mlindauer** [berndbischl/coseal-algsel-benchmark-repo#36]
the bbob set does not define a runtime cutoff.
however, there are timeouts and the value is Inf.

I think the value should be ? and the runtime cutoff should be added.

**Comment by kerschke** [comment]
the problem with the bbob timeout is, that it depends on the dimension..

**Comment by kerschke** [comment]
Any suggestions what kind of cutoff-time I should mention in the description? The only option I can think of is to mention it in the readme.txt and leave a "?" in the description.txt

**Comment by mlindauer** [comment]
please discuss it with Bernd.
I'm not familiar with bbob.

**Comment by kerschke** [comment]
Actually, you don't have to be familiar with bbob. It's more a question on how flexible our specifications are. Do we HAVE to add a cutoff-time - even though it changed per instance (observation)? Or would it be fine, if it is mentioned in the readme?!

Also, I would like to leave the value Inf as this has a different meaning compared to ? (or NA). However, again, it depends on the specifications.

**Comment by mlindauer** [comment]
good questions.

The problems, I see with the current data set:
- If we allow Inf as an performance value, all performance assessments with aggregation (e.g., sum) are useless if it is only once Inf.
- I don't know how could have measured Inf in practice. If it is indeed a performance metric there has to be an upper limit, right? 
- Can something be infinite bad?
- If you used a performance metric and there are missing values (?),
  we need some upper bound on the metric to calculate metrics like PAR10.

**Comment by kerschke** [comment]
Well, I guess one could also define it as "?", set the runstatus to "other" and mention it in the readme.
It looks like you're right and we should let Bernd decide :-)

**Comment by berndbischl** [comment]
RWeka:read.arff  cant handle Infs either I think

Create pages for: bbob_2013_master_thesis
Error in .jnew("weka/core/Instances", .jcast(reader, "java/io/Reader")) : 
  java.io.IOException: number expected, read Token[Inf], line 100

**Comment by kerschke** [comment]
I fixed the problem with the infinite values by setting them to ? (timeout) for the algo runs and to ? (other) for the feature values.
However, there still remains the problem of specifying the timeout. One possible solution would be to split the data per dimension - then I could give the specific timeouts. But this would actually just bloat our platform, so I don't really like this "solution".

**Comment by berndbischl** [comment]
Pascal, let us discuss this matter on Tuesday. 

I am currently too busy, and I need to ask you 1-2 things anyways.

**Comment by berndbischl** [comment]
Pascal, we discussed this.

Can we close?

**Comment by kerschke** [comment]
We forgot to discuss what we should do with the cutoff_time in the description. So far, we have a "?" there and I would add it to the readme. Is that satisfying enough?

**Comment by berndbischl** [comment]
I you cant give a single numerical value and explain it: yes.

**Comment by kerschke** [comment]
Not without splitting the data by dimension, which would only bloat the platform. Thus, I will do it as discussed (set a "?" and explain it in the readme).
