### ISSUE TITLE
bug in csp set (feature runstatus)

### ISSUE THREAD

**Issue by mlindauer** [berndbischl/coseal-algsel-benchmark-repo#37]
in feature_runstatus,
? is not possible value for status,
see

BlackHole-4-13-e-0_ext.xml.minion.converted.minion.gz,1,?
BlackHole-4-13-e-1_ext.xml.minion.converted.minion.gz,1,?
BlackHole-4-13-e-2_ext.xml.minion.converted.minion.gz,1,?
BlackHole-4-13-e-3_ext.xml.minion.converted.minion.gz,1,?
BlackHole-4-13-m-0_ext.xml.minion.converted.minion.gz,1,?
BlackHole-4-13-m-1_ext.xml.minion.converted.minion.gz,1,?
BlackHole-4-13-m-2_ext.xml.minion.converted.minion.gz,1,?

**Comment by kerschke** [comment]
Fixed it - as I don't have any further knowledge about the data, the runstatus was set to "other", if at least one feature within that observation/instance was NA.
Maybe Lars has some more details on the data...

**Comment by larskotthoff** [comment]
Hmm, looks like some features couldn't be computed because of memory out.

**Comment by kerschke** [comment]
so you propose we define their runstatus as "memout" instead of "other"?!

**Comment by larskotthoff** [comment]
I _think_ those were memouts, yes.

**Comment by kerschke** [comment]
then, it's done :-)
