### ISSUE TITLE
duplicated instances

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#38]
seems turned off in html
- check function, docs and test
- turn it on

**Comment by kerschke** [comment]
It was already included. Now, the test for it is included as well.

**Comment by berndbischl** [comment]
Should be more readable, at least add 1-3 spaces between instance names. 

I dont know, maybe we should also check the results with the people who provided them?

**Comment by kerschke** [comment]
But ain't that a problem of labeling the instance IDs? I mean, if they would not be that long, especially with all those slashes and so on, it would already be a lot more readable...
Otherwise, we could just print each duplicated instance in a separate row (as we did before). But I am not sure if that's a lot more readable.

**Comment by berndbischl** [comment]
The other guys love the long names with slashes.

Add spaces for now, it is not the most important part of the page. If you have a brilliant idea to make it more readable, please do it - a little bit later.

**Comment by kerschke** [comment]
Does anybody know how to implement a moving text in html like in a news ticker ;-)

**Comment by Cedric7** [comment]
you can write that:

<marquee behavior="scroll" direction="right">Here is some scrolling text... left to right!
</marquee>

Le Lundi 3 mars 2014 14h34, kerschke notifications@github.com a écrit :

Does anybody know how to implement a moving text in html like in a news ticker ;-)

**Comment by berndbischl** [comment]
Cedric, if you can improve the visuals here, do it. 
Otherwise close it, if that fails.

It is currently not that bad.

**Comment by berndbischl** [comment]
This is not so important right now. 

Closing, until somebody complains that it looks bad.
