### ISSUE TITLE
Format Spec: Unclear how EXPERIMENT repetitions are handled in CV

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#39]
Lars + Marius: We need to discuss this very soon.

**Comment by berndbischl** [comment]
Off topic: 
Can I somehow assign / notify multiple people for a issue?

**Comment by mlindauer** [comment]
I'm not quite sure whether I understand the issue. 
We have a free day at Monday here
so I could talk at Tuesday!?
(or write e-mails sometime before)

**Comment by berndbischl** [comment]
To clear this up I discussed it with Marius.

The CV folds define which instances go into training,which into tests.

It does not matter if we have stochastic replications on them for an instance, they either all go into train or all into test for that instance. So the format is OK and clear.

For experiments we currently average our such replications before we pass stuff to llama.

**Comment by berndbischl** [comment]
Closing, as format is OK as explained above.
