### ISSUE TITLE
Bug in EDA:  RUN OK 

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#42]
Why do we have 0% so often?

Check this for asp task. Features and algos both.

**Comment by mlindauer** [comment]
The problem is that I used uppercases and the eda scripts are casesensitive; my validator is not casesensitive.  
So, two ways too solve the problem.

**Comment by berndbischl** [comment]
You have to make the validator to in a check case-sensitive way.

Otherwise we will run into horrible problems on our end, as R is simply case-sensitive in that regard.

We also have to change the data sets then right?

**Comment by kerschke** [comment]
I just fixed the asp-potassco data. Now, the algorithm and feature EDA tables look better.

**Comment by kerschke** [comment]
I'll reassign this issue to Marius as it is now a validation problem - not a problem on the EDA side.

**Comment by berndbischl** [comment]
Has this been addressed now?

**Comment by berndbischl** [comment]
Marius, can this be addressed please so we reduce the number of open issues?

It cannot be hard to make this case sensitive in python right?

**Comment by mlindauer** [comment]
yes, it shouldn't be hard.
However, Kevin Tierney visits us this week.
Therefore, I have to postpone this minor problem a bit.

**Comment by berndbischl** [comment]
Is this done now?

**Comment by mlindauer** [comment]
ok, fixed in validator
