### ISSUE TITLE
Bug in EDA: Scatterplot matrix of the performance values

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#43]
check premarshalling_astar_2013/algos.html

**Comment by mlindauer** [comment]
I havent found a na/inf in the data but a 0 as runtime which may cause porblems on log scale.

**Comment by berndbischl** [comment]
Thanks, thats the poblem.

Logscale is configurable already. 

http://berndbischl.github.io/coseal-algsel-benchmark-repo/task-pages/premarshalling_astar_2013/config.html

I just turned it off. 

Now the plots look slightly worse,I will open another issue.
