### ISSUE TITLE
convertToLlama needs to impute features as well

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#46]
convertToLlama should not only impute the results of the algorithm runs, but also of the features. Otherwise, we get problems when classifying the data:

ASTask = parseASTask("../../coseal/data/csp_2010/")
LlamaTask = convertToLlama(ASTask)
res = classify(classifier=randomForest, data = cvFolds(LlamaTask, nfolds=2))
# Fehler in { : task 1 failed - "missing values in object"

**Comment by berndbischl** [comment]
How about actually looking into the code before reporting ;-) ?

```
  ### handle features ###
....

  #FIXME: maybe use a backup solver when some features are NA, instead of imputing
  # impute feature values
  # FIXME: why cant we impute without target
  feats$.y = 1
  feats = impute(feats, target = ".y")$data
  feats$.y =  NULL

```

I am preparing a 5 course meal right now, so you have to check the bug yourself.....

**Comment by kerschke** [comment]
I looked into it and saw that you already worked on it. So I thought it's best, if I let you fix your code ;-)

**Comment by berndbischl** [comment]
Please dont do it like this, I cant do everything simultaneously....

I work in "stages", so when I commit I _think_ it is OK / done for now.

If you find stuff like that at least try to figure out what is wrong and add more info, please.
Because apparently in this case there is some code for imputation already.

**Comment by berndbischl** [comment]
To make myself clear:

Of course REPORTING stuff has always preference, and should be done at once.

But IF you have 10 more minutes in cases like this, please try to invest them to figure out more info,
I do the same when I use your or he other guys code...

**Comment by kerschke** [comment]
Ok, I think, I just fixed that part. Now all missing feature values are imputed by the median of that feature.

**Comment by kerschke** [comment]
Damn... I remember we had this issue last week when I visited Bernd. I thought, I also changed it to imputing twice the maximum for numerical / integer values and creating a pseudo-category for character / factor features. Unfortunately, it looks like I haven't commited that change and also even deleted that change on my R code.
Thus, should I change it again (and commit it this time) or should we keep using the median? Of course, we would have to re-run the llama-experiments, but I thought we have to do this anyways (running it with 5 repetitions).

**Comment by berndbischl** [comment]
Pascal, what are you talking about here? Can this be closed? 
Because we DO impute feature NAs currently?

**Comment by kerschke** [comment]
Which part of my comment didn't you understand?
1) We talked about the imputation technique in your office.
2) You suggested that I should prog imputation by par2 for numerical values and creating an extra class for characters and categorical features.
3) It looks like I haven't committed the imputation like in 2) but still had the version of imputing with the median instead...
4) Should I commit the version from 2) before we re-run the experiments? Marius suggested, after reading about that in the paper, that we should keep the median-imputation for now.

**Comment by berndbischl** [comment]
Leave it like it is, I will go over it once then close this here.

**Comment by berndbischl** [comment]
I will open a new issue, imputation is currently done.
