### ISSUE TITLE
EDA error on features page, maxsat12-pms 

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#47]
See here

```
## Error: length of 'dimnames' [2] not equal to array extent
## Error: if argument 'digits' is a vector of length more than one, it must
## have length equal to 3 ( ncol(x) + 1 )
```

http://berndbischl.github.io/coseal-algsel-benchmark-repo/task-pages/maxsat12-pms/features.html

**Comment by kerschke** [comment]
Did you update your code? Because I actually fixed those lines a couple of hours BEFORE your post. And on my local html output, everything works...

**Comment by berndbischl** [comment]
I just browsed the online pages for some secs and wanted to report what I noticed.

Can you yourself run "make push-task-page"?
If not, ask me and do it in the future.

**Comment by kerschke** [comment]
I just tried it and it did not work. I'll work on it and/or check what the problem caused. However, if you want to have the most recent version online, you should run it for now :-)

**Comment by Cedric7** [comment]
i still tried <marquee behavior="scroll" direction="right">Here is some scrolling text... left to right!</marquee>
and it works perfect.

Le Lundi 3 mars 2014 14h40, kerschke notifications@github.com a écrit :

I just tried it and it did not work. I'll work on it and/or check what the problem caused. However, if you want to have the most recent version online, you should run it for now :-)

**Comment by Cedric7** [comment]
good  :-)

Le Lundi 3 mars 2014 15h17, Fankam Cedric cedfankam6@yahoo.fr a écrit :

i still tried <marquee behavior="scroll" direction="right">Here is some scrolling text... left to right!</marquee>
and it works perfect.

Le Lundi 3 mars 2014 14h40, kerschke notifications@github.com a écrit :

I just tried it and it did not work. I'll work on it and/or check what the problem caused. However, if you want to have the most recent version online, you should run it for now :-)

**Comment by berndbischl** [comment]
Cedric, I dont get the comments on this page....

**Comment by Cedric7** [comment]
i just answered the question of pascal about moving text html like a news ticker

Le Lundi 3 mars 2014 15h51, berndbischl notifications@github.com a écrit :

Cedric, I dont get the comments on this page....

**Comment by berndbischl** [comment]
Yes, but this is the wrong thread. Also you are constantly posting a "footer" below your mails.

Please use your browser to reply to the issue tracker instead.

**Comment by berndbischl** [comment]
EDA page seems ok now, closing.

**Comment by Cedric7** [comment]
it's now ok

**Comment by Cedric7** [comment]
sorry Pascal, i was a little unwell, I already sent u the example in your mail

**Comment by Cedric7** [comment]
i think about example html
