### ISSUE TITLE
problems with llama::classify

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#48]
I encountered problems when trying to run classify for various classifiers:

(1) Some classifiers (e.g. a randomForest) have problems when predicting a model for an empty class, which is not uncommon when doing cross-validations on small classes.
(2) We need to forward arguments:
(2a) When classifying with rpart, "predict" returns a probability matrix instead of the predicted classes. This causes problems when you intent to use a vector of classes and now have to handle a matrix with a lot more elements, e.g. in
_ensemblepredictions[, j] = as.character(predict(model, tsf$features))_
(2b) Another reason for forwarding arguments is the need for arguments within some classifiers such as the argument size in nnet.

**Comment by larskotthoff** [comment]
This is probably something that should be raised for LLAMA itself -- https://bitbucket.org/lkotthoff/llama

The short answer is that I'm aware of such issues. In the short term, nothing is going to happen about this, but in the medium term I'll probably switch LLAMA over to MLR, which offers a unified interface.

I'm not sure about forwarding arguments though -- is algselbench intended to be a wrapper for LLAMA?

**Comment by kerschke** [comment]
The problem is that this will restrict us to a very limited number of classifiers and/or regressors. Also, we are only able to run experiments in the default settings of those learners.
As long as all of you are aware of that, we can keep it this way, even though it's actually not very satisfying.

However, as you mentioned you will switch to mlr this shouldn't be an issue, because mlr allows to forward arguments.

**Comment by mlindauer** [comment]
I'm not an expert in R nor in LLAMA,
but I would like to understand what you meant with:
"Also, we are only able to run experiments in the default settings of those learners."?

I expected that LLAMA would automatically optimize the parameters of the learners (somehow)
because it is common knowledge that some learners can have arbitrary bad performance on default parameter settings. Am I wrong?

**Comment by larskotthoff** [comment]
LLAMA doesn't do any automatic optimisation of parameters (nor is it my intention to add this). If you want to do that, use any existing parameter tuner and wrap the LLAMA code in a suitable way.

Regarding the default settings comment, this really only refers to the fact that LLAMA currently doesn't support passing parameters through to the learners explicitly. However, you can wrap the learner in a function that sets the parameters as you like them. So basically LLAMA would see a learner with two different parameter sets as two learners.

I agree that overall this isn't optimal and it's on my list of things to do.

**Comment by berndbischl** [comment]
mlr would solve parameter and tuning issues. And I can help in designing a reasonable experimental setup. Please note that tuning will increase the runtimes A LOT. So we have to find some middle ground. I have done that like a million times, so I have a good gut feeling for how to do that.

I will now open up a issue in llama, to pass mlr learners to llama. I wanted to do that some time ago, I was just too busy. I mainly need the interface specification from Lars.

**Comment by berndbischl** [comment]
Closing, as we can apparently run a large number of models already.
