### ISSUE TITLE
qbf: timeout vs. memout

### ISSUE THREAD

**Issue by mlindauer** [berndbischl/coseal-algsel-benchmark-repo#49]
Hi Lars,

could you please check the qbf data.

Was the following really a timeout?
Umbrella_tbm_26.tex.moduleQ3.2S.000009,1,quantor,214.77,timeout

Furthermore, I would expect "?" in all cases of timeouts; also here:
Umbrella_tbm_26.tex.moduleQ3.2S.000014,1,2clsQ,3599.53,timeout

Cheers,
Marius

**Comment by larskotthoff** [comment]
Hi Marius, thanks for checking -- yes, those are indeed incorrect. There were quite a couple of memouts in there that I hadn't pulled from the status codes. I've just committed a fix that also puts '?' where the status was not ok.

Please verify and close or follow up.
