### ISSUE TITLE
Add explanation of measures in experimental results

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#55]
Lars, can you please do this in the html file:
Rhtml/llama.Rhtml

You know the exact defs. better than I do that are used in llama.

**Comment by larskotthoff** [comment]
Done in 2bef2bf78b8c9f2def16bced9555b3bf27b1393d. Let me know if you want more detailed descriptions.

**Comment by kerschke** [comment]
I just updated the html-pages.

**Comment by mlindauer** [comment]
- please add 10 at par (par10) since it could be also par2 or par100
- has the mcp also penalization of timeouts?

**Comment by berndbischl** [comment]
"The number of successes records the number of problem instances in the data set what were solved within the timeout."

If this is what is measured in the first column "best", the name "best" is rubbish and we should call the column - taadaa - "successes".

**Comment by kerschke** [comment]
I just changed the column names to "success ratio", "mcp" and "par10". Better?!

And Marius, I actually can't tell you how llama handles/penalizes timeouts for calculating the mcp. Lars?!

**Comment by larskotthoff** [comment]
I've clarified how timeouts are handled for mcp.

**Comment by larskotthoff** [comment]
Oh and I think success ratio is misleading -- I would say "percentage solved" or "timeout ratio" here.

**Comment by kerschke** [comment]
Ok, I updated the column names.

@mlindauer: I also fixed the satzilla data as you still had the attribute "total" listed within your feature_costs.

**Comment by mlindauer** [comment]
@kerschke: sorry

**Comment by berndbischl** [comment]
Can this be closed? Everybody OK with the current text?

**Comment by larskotthoff** [comment]
I'm ok with it.

**Comment by berndbischl** [comment]
Apparently the description is OK. Nobody complained.
