### ISSUE TITLE
Presolved / costs

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#56]
How do we respect in the experiments that we presolved an instance?

What are the costs then for presolving?

Dont we need to know the order of the feature computation then?

**Comment by mlindauer** [comment]
I added the requirement of an order in the specification
and updated accordingly the SAT and ASP data.
Only the BBOB data has also several steps. 
@kerschke : please check in the bbob description.arff that the steps are ordered accordingly to the execution sequence.

**Comment by kerschke** [comment]
The steps in BBOB are already in the correct order.
