### ISSUE TITLE
Check code of providing the overview table

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#59]
The new overview table at the index page looks good.
Unfortunately, there still seems to be a bug, because BBOB has stochastic algorithms, which is also mentioned within the description, but the table states "FALSE".

**Comment by berndbischl** [comment]
What I look at are whether there are repetitions.

**Comment by berndbischl** [comment]
For BBOB it is strange, that you put "stochastic algos" but only do one rep.

I could look at the description file in the table (like you did just now) and mention the nr of reps in brackets?

**Comment by kerschke** [comment]
Well, the data I provided was already aggregated. I already calculated the ERT, which is already based on 10 replications. Otherwise I would have to put in some work on preprocessing the original big data sets and provide it here. However, this will probably be a lot bigger and I'm not sure if we need this version right now.

**Comment by kerschke** [comment]
I thought you read my thesis ;-)

**Comment by kerschke** [comment]
It looks as if you solved that issue. Close?!

**Comment by berndbischl** [comment]
Yes fixed
