### ISSUE TITLE
Constant Features and Empty Classes

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#66]
This is just a reminder, because you removed two essential preprocessing steps while cleaning the functions:
Don't forget to remove **constant features** within the feature sets and **empty classes** in the training data. Otherwise some learners might crash.

**Comment by berndbischl** [comment]
Yes I know, I emailed myself about this :)

I still want to pull this into mlr. 

But maybe I cant, because we also use basic R/llama models?

Do you remember 1-2 tasks where these kinds of errors happened often?

**Comment by kerschke** [comment]
I think the sat12 data sets were more likely to produce those crashes.
Just try sat12-indu and some classifiers such as svm, ctree, etc.

**Comment by berndbischl** [comment]
Pascal, is this correct:
- there is no specific code left in the algselbench package for this
- everything now works

?

**Comment by berndbischl** [comment]
No errors occur anymore. Closing.
