### ISSUE TITLE
cluster methods: FarthestFirst SimpleKMeans maybe set nr of clusters

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#67]
maybe  set to nr of solvers

**Comment by kerschke** [comment]
At the moment, FarthestFirst and SimpleKMeans run with nr of clusters equal to nr of solvers.
In addition, XMeans and EM choose the ideal nr of clusters among 2, 3, ..., nr of solvers.

**Comment by berndbischl** [comment]
Please always describe stuff like this in the Rdocs!

**Comment by berndbischl** [comment]
```
        function(data) {
          wekaEM = make_Weka_clusterer("weka/clusterers/EM", 
                                       init = Weka_control(max = length(grep("_success", names(data$data)))))
          wekaEM(data)
        }
```

I also do not get how the code can work.
How can data be as simple data.frame that we pass to wekaEM(data) and at the same time a list with element "data", in data$data ?

**Comment by kerschke** [comment]
We do not pass a simple data frame to wekaEM, we pass an entire list.

```
task = convertToLlamaCVFolds(astask, add.feature.costs = TRUE)
wekaEM(data = task)
```

And one of the list elements (the first one) is called **data**.

**Comment by berndbischl** [comment]
This does not make sense.

Where in the RWEKA docs do you see that this is like it is supposed to be?

**Comment by berndbischl** [comment]
proof

> library(RWeka)
> wekaEM = make_Weka_clusterer("weka/clusterers/EM")
> data = list(data = iris[, 1:4])
> wekaEM(data)
> Error in read_data_into_Weka(x) : Type not implemented

**Comment by berndbischl** [comment]
Pascal, the original point was about the R docs.

Is this done? Can we close?

**Comment by kerschke** [comment]
Do you refer to the description of the function, such as @title, @description, @param, etc.?! If yes, then it is done.

**Comment by kerschke** [comment]
Did you actually check, what's going on in the cluster calculation? I mean, you registered that the function

```
        function(data) {
          wekaEM = make_Weka_clusterer("weka/clusterers/EM", 
                                       init = Weka_control(max = length(grep("_success", names(data$data)))))
          wekaEM(data)
        }
```

might be incorrect. However, looking at the source-code, you still use it.

**Comment by berndbischl** [comment]
So we never fixed this? 
And the cluster results are wrong?

**Comment by berndbischl** [comment]
The thing is, I never saw an error. 
I will still look at it tomorrow.

**Comment by larskotthoff** [comment]
Regarding the data$data, maybe there's confusion because this is the way it is in LLAMA -- the LLAMA data frame has a member $data that contains the actual data? LLAMA doesn't call the clustering function with that though, but with a single data frame that contains the feature values.

**Comment by berndbischl** [comment]
Is it really a data.frame in llama? Or a list? (that has the member $data)

Technically, I know that you CAN put a df in a df in R, because a df is mainly a list, but I hope you did not do it that way?

**Comment by larskotthoff** [comment]
Yes, sorry, you're right -- it's a list.

**Comment by larskotthoff** [comment]
I've just run EM without the mlr wrapper and without setting a max number of clusters and get an average PAR10 of 7474.717 on the CSP data set (MCP 107.7383), so very similar to the results on the website.

**Comment by berndbischl** [comment]
You mean the algselbench wrapper? Mlr is not really involed here right?

This is reassuring.

What do you think when you look at our code? It is still not really correct from how the function is used right?

**Comment by larskotthoff** [comment]
Yes, I've used algselbench to convert to llama and then clustered without mlr.

I'm not sure about the code to be honest -- I'm not familiar enough with mlr.

**Comment by berndbischl** [comment]
look at runLlamaModels 

mlr is not used for clustering, mlr does not support clustering.

I very directly call llama.

**Comment by larskotthoff** [comment]
Well from that it looks like the code that determines the number of clusters wouldn't work because at this point there's no `data$data` -- there's only the data frame with feature values. You cannot get the number of algorithms at this point.

**Comment by berndbischl** [comment]
exactly. but i got no errors, but results instead.

apparently consistent with yours.

 which is strange?

**Comment by kerschke** [comment]
My guess is that llama somehow ignores the wrong argument.
Can we fix it somehow, i.e., derive the number of algos?

**Comment by berndbischl** [comment]
of course i can repair this

I would still like to understand what goes on.

**Comment by larskotthoff** [comment]
Well `names(data$data)` is `NULL`, so `grep` returns 0. The number of clusters is always set to 0, which RWeka probably interprets as "do your thing".

**Comment by berndbischl** [comment]
i will look at this tomorrow, fix and rerun just the clustering to check

**Comment by kerschke** [comment]
So RWeka actually allows 0 as a valid input for the number of clusters? Could be a solution but what will RWeka actually do? It still has to set the number of clusters to a certain value.

**Comment by berndbischl** [comment]
We will set the nr of clusters correctly. this is no problem.

**Comment by larskotthoff** [comment]
Hmm, the RWeka/Weka documentation doesn't say, but doesn't say that 0 isn't allowed either. Use the source :)

**Comment by berndbischl** [comment]
@all: I checked the code in debug mode now.
clusters were set to 0. 
This means that for EM we selected clusters by cross-val.
For others we probably took the default, which might have been 2. 
We need to rerun. 

@Pascal:
What I meant wrt to the rdocs was if you implement behavior like setting the nr of clusters, you need to of course DOCUMENT that for the user. I will do that now. But it is important that we dont do something like that hidden in the code and invisible for the user!

**Comment by berndbischl** [comment]
I will take care of this and close soon.

**Comment by berndbischl** [comment]
Close now, will rerun tomorrow.
