### ISSUE TITLE
Different Algorithms on different instances

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#68]
Do we permit that a task uses different algorithms on different instances?
I just checked Joaquin's machine_learning_uci_weka_defaults task and encountered problems within some of the EDA part - due to the problems mentioned above.

In case, you don't understand what I mean, here's an example:
Lets say we have 2 instances (inst1, inst2) and 4 algorithms (alg1, ..., alg4). Now, we have results (or at least missing values) from alg1 and alg2 on inst1 and we have results (or at least missing values) from alg2 - alg4 on inst2.
Is that ok? To me, this sounds very strange - why would I run different algos on different instances, however, I could not find anything within the specs that's explicitly prohibitting it.
Thus, if it's not allowed, we might have to add something to the specs (and update the problematic task).
Otherwise, I would have to fix the EDA scripts accordingly.

**Comment by mlindauer** [comment]
I agree that we should have the same algorithms (and same repetition) for each instance.
I will add a sentence in the specification (tomorrow).

Please write Joaquin a mail!

**Comment by kerschke** [comment]
What do you mean by same repetition for each instance? Do you actually mean the same algorithm for each instance and each of its repetitions?

Or do you really mean that each instance should have the same number of repetitions? I mean, I'm ok with that restriction as well, but from my point of view it's not as necessary as the algorithm problem.

**Comment by mlindauer** [comment]
to be precise:
The tuple (algorithm,#repetition) should be the same for all instances.
Ok?

**Comment by berndbischl** [comment]
Marius, I agree.
- Is it in the specs? 
- Checked in validator?

Close then?
