### ISSUE TITLE
Nominal values instead of STRING in ARFF

### ISSUE THREAD

**Issue by joaquinvanschoren** [berndbischl/coseal-algsel-benchmark-repo#69]
Just a tip: In the ARFF format, STRING is meant for arbitrary strings. For dataset instances and algorithms, it is better to use the nominal data type, expressed as a set, e.g. @ATTRIBUTE algorithm {algo1, algo2, algo3, ...}

That way you can also study the data distribution in tools such as WEKA, and check for errors (e.g. whether all algorithms are run on all instances).

**Comment by mlindauer** [comment]
since we have so many different instances, it would be really ugly to list them all in the header. We won't fix this.
