### ISSUE TITLE
EDA: We should not remove crashed / timed-out algorithms in the plots

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#76]
This gives a skewed picture of what happened.

Their performance value should be imputed to something like 2 \* cutoff or 2 \* worst performance.

**Comment by Cedric7** [comment]
For the plotting of cluster's coorelation, i suggest :
- to consider generally the rank-correlation. Then there is no dependence on any Trafos like log
- Missing values on 2 \* max  (or 2*min for maximize = TRUE)

**Comment by kerschke** [comment]
Also do it for the other plots - not only the cluster correlation plot.

**Comment by kerschke** [comment]
And I am still not sure, whether 2_max (2_min respectively) is ideal.

Imagine the following scenario:
- we want to maximize our measure (e.g., percentage solved or something like that)
- we have positive values (and NAs), e.g., in the range of 30-90%
- imputing with 2*min would give us a value of 60% for all the NAs, which is clearly not an outlier
- thus, i'd suggest to impute with "min - (max - min)" for maximization problems (in this case -30%) and "max + (max - min)" for minimization problems
- also, when we have a clear range of possible values for the performance measure, such as the percentage above (which should always be between 0 and 100%), I am not sure, if we want to impute with values outside that range

**Comment by berndbischl** [comment]
> thus, i'd suggest to impute with "min - (max - min)" for maximization problems (in this case -30%) and 
> "max + (max - min)" for minimization problems

Do it. 

Maybe with "min - 0.1 (max - min)" so we do not go too far from the orig range and skew the plots

**Comment by kerschke** [comment]
I just added the imputation to the scatterplot matrix. You should have a look at it, before I also add it to the other plots as well.

**Comment by berndbischl** [comment]
Pascal, can this now be closed as i opened a more specific issue #82?

**Comment by kerschke** [comment]
Works for me.
