### ISSUE TITLE
imputeCrashedRuns is bad

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#82]
It only imputes the object algo.runs but, as documented, the performance is stored also in algo.perf.

Which means the resulting task is now inconsistent!

**Comment by berndbischl** [comment]
Also:

We only impute when runstatus != "ok"

This is in general reasonable but we really need to check whether NAs occur in algo performance if runstatus is OK. (Which would be a data error IMHO)

**Comment by berndbischl** [comment]
Also why dont we impute for plotAlgoCorMatrix?

**Comment by kerschke** [comment]
NAs within runstatus == "ok" can't occur, as the validator checks for stuff like that.

**Comment by kerschke** [comment]
Also, it only imputes the data that is relevant for the plots in order to avoid unnecessary computations. But if you think it's important to add that as well, I could have a look at the function again.

**Comment by kerschke** [comment]
And comming to your last concern: I don't like the idea of imputing values and making the ranks. Because in that case, the value of the noise-parameter (which is used during imputations) has a lot more influence.
Also, for calculating the correlation matrix, only pairwise complete observations are used. Thus, we do not remove entire instances, only the ones that would cause problems for that specific pair of algorithms.

**Comment by berndbischl** [comment]
My original suggestion was to impute, but without jittering.

**Comment by kerschke** [comment]
In that case we do not have to impute but assign all those NAs the highest ranks. Then there is the question, whether equal values should receive an equal rank or an average rank.

**Comment by berndbischl** [comment]
Also, consider this case:

Algo A and B timeout 90% of the time, on the same instances.

On the rest, it is random whether A or B is better. 

Now are these two correlated? 
I would say "yes"?

Does our measure express this?

**Comment by kerschke** [comment]
I'm not sure, if I would consider them correlated, just because both of them crashed / timed out / etc.

**Comment by berndbischl** [comment]
Well to make it more clear:

i) A and B timeout BOTH on the later half of the instances. On the rest there is no clear winner.

ii) A and B timeout on exactly different 50% of the instances.

In i) It does not matter whether we select A or B.
In ii) it does, if we can figure out when A or B times out, given an instance and its features.

 I see it that in i) there is a correlation - "if A is extremely bad, B is bad too"
In ii) there is an anticorrelation, if A is bad, B is good, and vice versa.

**Comment by berndbischl** [comment]
Done. It is documented how we impute. Might not be perfect, but whatever.
