### ISSUE TITLE
findUseless seems bad

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#84]
1) Why is an algo useless if its performance is constant?
Is the description bad? Or is this simply wrong. EG an algorithm might have constantly runtime 0 and be therefore the best. It is certainly not useless then.

2) Also the function where this is computed is then called findUselessINSTANCES.....

**Comment by kerschke** [comment]
Then give it a more reasonable name, e.g., constant solvers.

And in your example (constantly runtime 0), the solver might not be useless, but one obviously wants to see that a solver produces such a constant output.

**Comment by berndbischl** [comment]
We removed it, closing.
