### ISSUE TITLE
EDA: All plots: We CANNOT drop data

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#85]
From the webpage:

"If the performance is represented on a log-scale, all non-positive performance values were removed."

This is of course bad. 

NEVER drop data in such a way.

**Comment by kerschke** [comment]
I've already mentioned this problem a couple of times. And your response was more or less: in case of non-negative values, one should not use a log-scale.
However, if one still forces to produce the output using a log-scale, this is the only solution I could think of.

**Comment by berndbischl** [comment]
We dont drop anymore but produce an error instead.
