### ISSUE TITLE
EDA: plotCorMatrix

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#87]
I thought we agreed upon correlation between ranks?
So spearmans rho.

This should be used on the server plots and be made the default in the method.

**Comment by kerschke** [comment]
I know we have agreed on using ranks and therefore the ranks of the data are calculated prior to calculating the correlation. Thus, we actually calculate spearmans rho ;-)

**Comment by berndbischl** [comment]
I changed the code to what I said should be done. Closing.
