### ISSUE TITLE
Consistent Scenario Names

### ISSUE THREAD

**Issue by kerschke** [berndbischl/coseal-algsel-benchmark-repo#88]
Scenario names (algorithm selection tasks) should be consistent within the entire paper (figures, text, captions, etc.).
Following idea:
- always uppercase
- dashes, but no underscores

**Comment by kerschke** [comment]
Done, within the paper.
However, we might have to change some of the figures within the paper as well (as not all scenario names are consistent to those properties from above).

**Comment by berndbischl** [comment]
Example pls?

**Comment by kerschke** [comment]
Have a look at your heatmap:
- Potassco instead of POTASSCO (uppercase)
- CSP_2010 instead of CSP-2010 (dash)
- MaxSAT-pms instead of MAXSAT-PMS (uppercase)
- premarshalling_astar_2013 instead of PREMARSHALLING-ASTAR-2013 (both)
- QBF_2011 instead of QBF-2011

**Comment by berndbischl** [comment]
Everything which is specifically generated for the paper is already correct. 

I probably did not have time to run the code again. 

Look at results_utils.R in the svn.

**Comment by kerschke** [comment]
Ok. I fixed the heatmap. Now everything _should_ be consistent.
