### ISSUE TITLE
shortenPathsInValidator

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#89]
1) The function is wrongly documented!

2) I dont think this belongs in the package, but into server scripts!

Please fix.

**Comment by berndbischl** [comment]
It is also not commented, which means it is very hard to understand.

I also see quite a lot of copy-paste.

**Comment by kerschke** [comment]
Moved it to the server scripts package, reduced copy-paste parts and changed the corresponding documentation.
