### ISSUE TITLE
ARFF does not have a Boolean column type

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#9]
ARFF does not have a "Boolean" column type. We need to change this, otherwise we have invalid files.

http://weka.wikispaces.com/ARFF

What did we say in the specs? Change this too?

**Comment by mlindauer** [comment]
I changed it to 
@ATTRIBUTE presolved {true,false}

**Comment by berndbischl** [comment]
a) 
Check / Convert maxsat12-pms data set.

b)
Check that "Boolean" type is not in your specification latex file anymore.

**Comment by kerschke** [comment]
a) Converted maxsat12-pms data set.
b) Changed the one appeareance of "boolean" in the description of feature_runstatus.arff (within the specification tex file).
