### ISSUE TITLE
runstatus == "ok" vs NA in algo perf

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/coseal-algsel-benchmark-repo#90]
Really make sure that this is the same thing.

Check both directions:
  "OK" <==> there is a value
  not "OK" <==>  there is NA

Discuss with Marius how this is checked in the validator.
It is documented?

**Comment by mlindauer** [comment]
already checked in validator.

**Comment by mlindauer** [comment]
we changed the specification such that NA are not allowed in algo perf.
